"""postgresql_baseline — PostgreSQL Migration Epoch root (Phase 2D.1-P)

The single root of the active, PostgreSQL-only Alembic chain
(``migrations/postgresql_versions/``), replacing
``migrations/versions/`` (the pre-2D.1-P SQLite-era chain, frozen at the
LEGACY MIGRATION FREEZE ANCHOR commit
b94f572528e25a620bf1a78bd2e26d12547b0212 — left in the repository
untouched as inert historical reference, never wired into active Alembic
tooling again).

This is a persistence-layer rebaseline, NOT a business-schema redesign:
it re-expresses the exact Phase 2D.1 schema and every storage invariant
(one-current/one-initial revision partial indexes, the
ProcurementSalesLink one-current-episode trigger, correction lineage,
whole-fact supersession, every CHECK constraint, every FK) using
PostgreSQL-native constructs, generated from ``Base.metadata`` via
``alembic revision --autogenerate`` against an empty PostgreSQL database
and hand-completed only where autogenerate cannot express DDL (the
trigger function/trigger below — DDL events aren't part of SQLAlchemy's
metadata diff). See docs/PERSISTENCE-MIGRATION-POLICY.md for the full
rationale, including why the old chain could not be replayed as-is (a
raw SQLite-only trigger statement in
migrations/versions/f1a2b3c4d5e6_procurement_sales_link.py is a hard
PostgreSQL syntax error) and why this is a one-time, non-repeatable
exception to migration immutability rather than an edit to that frozen
file.

PostgreSQL-only by design: refuses to run against any other dialect
(see the guard at the top of ``upgrade()``) rather than reproducing
SQLite mechanisms for historical similarity. SQLite remains a test-only
convenience via ``Base.metadata.create_all()`` (unaffected by this
chain).

Revision ID: f5796c006707
Revises:
Create Date: 2026-08-30 21:34:37.548960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5796c006707'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_ONE_CURRENT_LINK_TRIGGER_POSTGRESQL = """
CREATE FUNCTION trg_procurement_sales_links_one_current_fn() RETURNS TRIGGER AS $$
BEGIN
    PERFORM pg_advisory_xact_lock(
        hashtextextended(NEW.procurement_contract_id::text || ':' || NEW.sales_contract_id::text, 0)
    );
    IF EXISTS (
        SELECT 1 FROM procurement_sales_links existing
        WHERE existing.procurement_contract_id = NEW.procurement_contract_id
          AND existing.sales_contract_id = NEW.sales_contract_id
          AND NOT EXISTS (
              SELECT 1 FROM procurement_sales_link_corrections c
              WHERE c.superseded_link_id = existing.id
          )
    ) THEN
        RAISE EXCEPTION 'one current assertion episode per relationship business key';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_procurement_sales_links_one_current
BEFORE INSERT ON procurement_sales_links
FOR EACH ROW
EXECUTE FUNCTION trg_procurement_sales_links_one_current_fn();
"""


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        raise RuntimeError(
            f"the PostgreSQL Migration Epoch chain (migrations/postgresql_versions/) only runs "
            f"against PostgreSQL — got dialect {bind.dialect.name!r}. SQLite is a test-only "
            "convenience via Base.metadata.create_all(), never via this Alembic chain."
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_events_event_type'), ['event_type'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_no', sa.String(), nullable=False),
    sa.Column('counterparty', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_contract_no'), ['contract_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_counterparty'), ['counterparty'], unique=False)

    op.create_table('evidence_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_documents_sha256'), ['sha256'], unique=True)

    op.create_table('match_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('match_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_cases_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_cases_subject_type'), ['subject_type'], unique=False)

    op.create_table('sales_contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('our_entity', sa.String(), nullable=False),
    sa.Column('sales_contract_no', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('our_entity', 'sales_contract_no', name='uq_sales_contract_business_identity')
    )
    with op.batch_alter_table('sales_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_contracts_our_entity'), ['our_entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_contracts_sales_contract_no'), ['sales_contract_no'], unique=False)

    op.create_table('task_exceptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exception_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_exceptions_exception_type'), ['exception_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_exceptions_status'), ['status'], unique=False)

    op.create_table('contract_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('source_item_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'source_item_key', name='uq_contract_item_source_key')
    )
    with op.batch_alter_table('contract_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_items_contract_id'), ['contract_id'], unique=False)

    op.create_table('evidence_fragments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=False),
    sa.Column('fragment_kind', sa.String(), nullable=False),
    sa.Column('sheet_name', sa.String(), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('locator_json', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['evidence_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_document_id', 'sheet_name', 'row_number', name='uq_fragment_location')
    )
    with op.batch_alter_table('evidence_fragments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_fragments_evidence_document_id'), ['evidence_document_id'], unique=False)

    op.create_table('import_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('is_reimport', sa.Boolean(), nullable=False),
    sa.Column('contracts_created_count', sa.Integer(), nullable=False),
    sa.Column('contract_items_created_count', sa.Integer(), nullable=False),
    sa.Column('business_key_conflicts_detected_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['evidence_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_runs_evidence_document_id'), ['evidence_document_id'], unique=False)

    op.create_table('match_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_case_id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['match_case_id'], ['match_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_candidates_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_candidates_match_case_id'), ['match_case_id'], unique=False)

    op.create_table('sales_match_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_case_id', sa.Uuid(), nullable=False),
    sa.Column('sales_contract_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_case_id'], ['match_cases.id'], ),
    sa.ForeignKeyConstraint(['sales_contract_id'], ['sales_contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_case_id', 'sales_contract_id', name='uq_sales_match_candidates_case_target')
    )
    with op.batch_alter_table('sales_match_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_match_candidates_match_case_id'), ['match_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_match_candidates_sales_contract_id'), ['sales_contract_id'], unique=False)

    op.create_table('shipments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('external_reference', sa.String(), nullable=True),
    sa.Column('execution_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'external_reference', 'execution_date', name='uq_shipment_business_identity')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_contract_id'), ['contract_id'], unique=False)

    op.create_table('accrual_basis_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('contract_item_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('basis', sa.String(), nullable=False),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_by_fact_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['contract_item_id'], ['contract_items.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_fact_id'], ['accrual_basis_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accrual_basis_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accrual_basis_facts_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accrual_basis_facts_contract_item_id'), ['contract_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accrual_basis_facts_superseded_by_fact_id'), ['superseded_by_fact_id'], unique=False)

    op.create_table('accruals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('contract_item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('basis', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_from_fact_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_item_id'], ['contract_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accruals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accruals_contract_item_id'), ['contract_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accruals_created_from_fact_id'), ['created_from_fact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accruals_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_accruals_status'), ['status'], unique=False)

    op.create_table('contract_item_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_item_id', sa.Uuid(), nullable=False),
    sa.Column('revision_type', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('specification', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=True),
    sa.Column('superseded_by_revision_id', sa.Uuid(), nullable=True),
    sa.Column('asserted_field_names', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("revision_type IN ('INITIAL', 'SUPPLEMENT', 'CORRECTION')", name='ck_contract_item_revisions_revision_type'),
    sa.ForeignKeyConstraint(['contract_item_id'], ['contract_items.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_revision_id'], ['contract_item_revisions.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_item_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_item_revisions_contract_item_id'), ['contract_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_item_revisions_superseded_by_revision_id'), ['superseded_by_revision_id'], unique=False)
        batch_op.create_index('uq_contract_item_revisions_one_current', ['contract_item_id'], unique=True, sqlite_where=sa.text('superseded_by_revision_id IS NULL'), postgresql_where=sa.text('superseded_by_revision_id IS NULL'))
        batch_op.create_index('uq_contract_item_revisions_one_initial', ['contract_item_id'], unique=True, sqlite_where=sa.text("revision_type = 'INITIAL'"), postgresql_where=sa.text("revision_type = 'INITIAL'"))

    op.create_table('contract_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('revision_type', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('buyer', sa.String(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=True),
    sa.Column('superseded_by_revision_id', sa.Uuid(), nullable=True),
    sa.Column('asserted_field_names', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("revision_type IN ('INITIAL', 'SUPPLEMENT', 'CORRECTION')", name='ck_contract_revisions_revision_type'),
    sa.CheckConstraint('superseded_by_revision_id IS NOT NULL OR (gross_amount IS NOT NULL AND currency IS NOT NULL)', name='ck_contract_revisions_current_requires_amount_currency'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_revision_id'], ['contract_revisions.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_revisions_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_revisions_superseded_by_revision_id'), ['superseded_by_revision_id'], unique=False)
        batch_op.create_index('uq_contract_revisions_one_current', ['contract_id'], unique=True, sqlite_where=sa.text('superseded_by_revision_id IS NULL'), postgresql_where=sa.text('superseded_by_revision_id IS NULL'))
        batch_op.create_index('uq_contract_revisions_one_initial', ['contract_id'], unique=True, sqlite_where=sa.text("revision_type = 'INITIAL'"), postgresql_where=sa.text("revision_type = 'INITIAL'"))

    op.create_table('cost_recognition_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('recognition_date', sa.Date(), nullable=False),
    sa.Column('basis', sa.String(), nullable=False),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_by_fact_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_fact_id'], ['cost_recognition_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_recognition_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_recognition_facts_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_recognition_facts_superseded_by_fact_id'), ['superseded_by_fact_id'], unique=False)

    op.create_table('historical_accrual_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_period', sa.String(), nullable=False),
    sa.Column('contract_item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('basis', sa.String(), nullable=False),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_by_fact_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['contract_item_id'], ['contract_items.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_fact_id'], ['historical_accrual_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_accrual_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_accrual_facts_contract_item_id'), ['contract_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_accrual_facts_source_period'), ['source_period'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_accrual_facts_superseded_by_fact_id'), ['superseded_by_fact_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('invoice_type', sa.String(), nullable=True),
    sa.Column('invoice_no', sa.String(), nullable=True),
    sa.Column('digital_invoice_no', sa.String(), nullable=True),
    sa.Column('external_invoice_key', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('seller', sa.String(), nullable=True),
    sa.Column('buyer', sa.String(), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('invoice_status', sa.String(), nullable=True),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_external_invoice_key'), ['external_invoice_key'], unique=True)

    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('counterparty', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('bank_reference', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('running_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_account_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_source_account_id'), ['source_account_id'], unique=False)

    op.create_table('procurement_sales_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('procurement_contract_id', sa.Uuid(), nullable=False),
    sa.Column('sales_contract_id', sa.Uuid(), nullable=False),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('confirmation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("confirmation_type IN ('AUTO_CONFIRMED', 'HUMAN_CONFIRMED')", name='ck_procurement_sales_links_confirmation_type'),
    sa.ForeignKeyConstraint(['procurement_contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['sales_contract_id'], ['sales_contracts.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procurement_sales_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procurement_sales_links_procurement_contract_id'), ['procurement_contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurement_sales_links_sales_contract_id'), ['sales_contract_id'], unique=False)

    op.create_table('sales_contract_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sales_contract_id', sa.Uuid(), nullable=False),
    sa.Column('revision_type', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('superseded_by_revision_id', sa.Uuid(), nullable=True),
    sa.Column('asserted_field_names', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("revision_type IN ('INITIAL', 'SUPPLEMENT', 'CORRECTION')", name='ck_sales_contract_revisions_revision_type'),
    sa.ForeignKeyConstraint(['sales_contract_id'], ['sales_contracts.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_revision_id'], ['sales_contract_revisions.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_contract_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_contract_revisions_sales_contract_id'), ['sales_contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_contract_revisions_superseded_by_revision_id'), ['superseded_by_revision_id'], unique=False)
        batch_op.create_index('uq_sales_contract_revisions_one_current', ['sales_contract_id'], unique=True, sqlite_where=sa.text('superseded_by_revision_id IS NULL'), postgresql_where=sa.text('superseded_by_revision_id IS NULL'))
        batch_op.create_index('uq_sales_contract_revisions_one_initial', ['sales_contract_id'], unique=True, sqlite_where=sa.text("revision_type = 'INITIAL'"), postgresql_where=sa.text("revision_type = 'INITIAL'"))

    op.create_table('shipment_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('revision_type', sa.String(), nullable=False),
    sa.Column('contract_item_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('superseded_by_revision_id', sa.Uuid(), nullable=True),
    sa.Column('asserted_field_names', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("revision_type IN ('INITIAL', 'SUPPLEMENT', 'CORRECTION')", name='ck_shipment_revisions_revision_type'),
    sa.ForeignKeyConstraint(['contract_item_id'], ['contract_items.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_revision_id'], ['shipment_revisions.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_revisions_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_revisions_superseded_by_revision_id'), ['superseded_by_revision_id'], unique=False)
        batch_op.create_index('uq_shipment_revisions_one_current', ['shipment_id'], unique=True, sqlite_where=sa.text('superseded_by_revision_id IS NULL'), postgresql_where=sa.text('superseded_by_revision_id IS NULL'))
        batch_op.create_index('uq_shipment_revisions_one_initial', ['shipment_id'], unique=True, sqlite_where=sa.text("revision_type = 'INITIAL'"), postgresql_where=sa.text("revision_type = 'INITIAL'"))

    op.create_table('invoice_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('match_case_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('match_method', sa.String(), nullable=False),
    sa.Column('confirmation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['match_case_id'], ['match_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_allocations_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_allocations_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_allocations_match_case_id'), ['match_case_id'], unique=False)

    op.create_table('invoice_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('specification', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_items_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('match_case_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('match_method', sa.String(), nullable=False),
    sa.Column('confirmation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['match_case_id'], ['match_cases.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_match_case_id'), ['match_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_payment_id'), ['payment_id'], unique=False)

    op.create_table('procurement_sales_link_corrections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('superseded_link_id', sa.Uuid(), nullable=False),
    sa.Column('replacement_link_id', sa.Uuid(), nullable=True),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('confirmation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("confirmation_type = 'HUMAN_CONFIRMED'", name='ck_procurement_sales_link_corrections_confirmation_type'),
    sa.ForeignKeyConstraint(['replacement_link_id'], ['procurement_sales_links.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.ForeignKeyConstraint(['superseded_link_id'], ['procurement_sales_links.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('superseded_link_id')
    )
    op.execute(_ONE_CURRENT_LINK_TRIGGER_POSTGRESQL)
    op.create_table('sales_invoice_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('sales_contract_id', sa.Uuid(), nullable=False),
    sa.Column('match_case_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('confirmation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("confirmation_type = 'HUMAN_CONFIRMED'", name='ck_sales_invoice_allocations_confirmation_type'),
    sa.CheckConstraint(f'allocated_gross_amount < {10 ** 16}', name='ck_sales_invoice_allocations_max_amount'),
    sa.CheckConstraint('allocated_gross_amount > 0', name='ck_sales_invoice_allocations_positive_amount'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['match_case_id'], ['match_cases.id'], ),
    sa.ForeignKeyConstraint(['sales_contract_id'], ['sales_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_invoice_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_invoice_allocations_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoice_allocations_match_case_id'), ['match_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoice_allocations_sales_contract_id'), ['sales_contract_id'], unique=False)

    op.create_table('sales_payment_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('sales_contract_id', sa.Uuid(), nullable=False),
    sa.Column('match_case_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('confirmation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("confirmation_type = 'HUMAN_CONFIRMED'", name='ck_sales_payment_allocations_confirmation_type'),
    sa.CheckConstraint(f'allocated_amount < {10 ** 16}', name='ck_sales_payment_allocations_max_amount'),
    sa.CheckConstraint('allocated_amount > 0', name='ck_sales_payment_allocations_positive_amount'),
    sa.ForeignKeyConstraint(['match_case_id'], ['match_cases.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['sales_contract_id'], ['sales_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_payment_allocations_match_case_id'), ['match_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_payment_allocations_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_payment_allocations_sales_contract_id'), ['sales_contract_id'], unique=False)

    op.create_table('invoice_item_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_item_id', sa.Uuid(), nullable=False),
    sa.Column('contract_item_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('allocated_net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('confirmation_type', sa.String(), nullable=False),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_by_fact_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['contract_item_id'], ['contract_items.id'], ),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['invoice_items.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_fact_id'], ['invoice_item_allocations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_item_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_item_allocations_contract_item_id'), ['contract_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_item_allocations_invoice_item_id'), ['invoice_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_item_allocations_superseded_by_fact_id'), ['superseded_by_fact_id'], unique=False)

    op.create_table('accrual_reversals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('accrual_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('invoice_item_allocation_id', sa.Uuid(), nullable=False),
    sa.Column('reversed_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reversed_estimated_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accrual_id'], ['accruals.id'], ),
    sa.ForeignKeyConstraint(['invoice_item_allocation_id'], ['invoice_item_allocations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accrual_reversals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accrual_reversals_accrual_id'), ['accrual_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accrual_reversals_invoice_item_allocation_id'), ['invoice_item_allocation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        raise RuntimeError(
            f"the PostgreSQL Migration Epoch chain (migrations/postgresql_versions/) only runs "
            f"against PostgreSQL — got dialect {bind.dialect.name!r}."
        )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accrual_reversals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accrual_reversals_invoice_item_allocation_id'))
        batch_op.drop_index(batch_op.f('ix_accrual_reversals_accrual_id'))

    op.drop_table('accrual_reversals')
    with op.batch_alter_table('invoice_item_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_item_allocations_superseded_by_fact_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_item_allocations_invoice_item_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_item_allocations_contract_item_id'))

    op.drop_table('invoice_item_allocations')
    with op.batch_alter_table('sales_payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_payment_allocations_sales_contract_id'))
        batch_op.drop_index(batch_op.f('ix_sales_payment_allocations_payment_id'))
        batch_op.drop_index(batch_op.f('ix_sales_payment_allocations_match_case_id'))

    op.drop_table('sales_payment_allocations')
    with op.batch_alter_table('sales_invoice_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoice_allocations_sales_contract_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_allocations_match_case_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoice_allocations_invoice_id'))

    op.drop_table('sales_invoice_allocations')
    op.execute("DROP TRIGGER IF EXISTS trg_procurement_sales_links_one_current ON procurement_sales_links")
    op.execute("DROP FUNCTION IF EXISTS trg_procurement_sales_links_one_current_fn()")
    op.drop_table('procurement_sales_link_corrections')
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocations_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_match_case_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_contract_id'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_items_invoice_id'))

    op.drop_table('invoice_items')
    with op.batch_alter_table('invoice_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_allocations_match_case_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_allocations_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_allocations_contract_id'))

    op.drop_table('invoice_allocations')
    with op.batch_alter_table('shipment_revisions', schema=None) as batch_op:
        batch_op.drop_index('uq_shipment_revisions_one_initial', sqlite_where=sa.text("revision_type = 'INITIAL'"), postgresql_where=sa.text("revision_type = 'INITIAL'"))
        batch_op.drop_index('uq_shipment_revisions_one_current', sqlite_where=sa.text('superseded_by_revision_id IS NULL'), postgresql_where=sa.text('superseded_by_revision_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_shipment_revisions_superseded_by_revision_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_revisions_shipment_id'))

    op.drop_table('shipment_revisions')
    with op.batch_alter_table('sales_contract_revisions', schema=None) as batch_op:
        batch_op.drop_index('uq_sales_contract_revisions_one_initial', sqlite_where=sa.text("revision_type = 'INITIAL'"), postgresql_where=sa.text("revision_type = 'INITIAL'"))
        batch_op.drop_index('uq_sales_contract_revisions_one_current', sqlite_where=sa.text('superseded_by_revision_id IS NULL'), postgresql_where=sa.text('superseded_by_revision_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_sales_contract_revisions_superseded_by_revision_id'))
        batch_op.drop_index(batch_op.f('ix_sales_contract_revisions_sales_contract_id'))

    op.drop_table('sales_contract_revisions')
    with op.batch_alter_table('procurement_sales_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procurement_sales_links_sales_contract_id'))
        batch_op.drop_index(batch_op.f('ix_procurement_sales_links_procurement_contract_id'))

    op.drop_table('procurement_sales_links')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_source_account_id'))

    op.drop_table('payments')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_external_invoice_key'))

    op.drop_table('invoices')
    with op.batch_alter_table('historical_accrual_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_accrual_facts_superseded_by_fact_id'))
        batch_op.drop_index(batch_op.f('ix_historical_accrual_facts_source_period'))
        batch_op.drop_index(batch_op.f('ix_historical_accrual_facts_contract_item_id'))

    op.drop_table('historical_accrual_facts')
    with op.batch_alter_table('cost_recognition_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_recognition_facts_superseded_by_fact_id'))
        batch_op.drop_index(batch_op.f('ix_cost_recognition_facts_contract_id'))

    op.drop_table('cost_recognition_facts')
    with op.batch_alter_table('contract_revisions', schema=None) as batch_op:
        batch_op.drop_index('uq_contract_revisions_one_initial', sqlite_where=sa.text("revision_type = 'INITIAL'"), postgresql_where=sa.text("revision_type = 'INITIAL'"))
        batch_op.drop_index('uq_contract_revisions_one_current', sqlite_where=sa.text('superseded_by_revision_id IS NULL'), postgresql_where=sa.text('superseded_by_revision_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_contract_revisions_superseded_by_revision_id'))
        batch_op.drop_index(batch_op.f('ix_contract_revisions_contract_id'))

    op.drop_table('contract_revisions')
    with op.batch_alter_table('contract_item_revisions', schema=None) as batch_op:
        batch_op.drop_index('uq_contract_item_revisions_one_initial', sqlite_where=sa.text("revision_type = 'INITIAL'"), postgresql_where=sa.text("revision_type = 'INITIAL'"))
        batch_op.drop_index('uq_contract_item_revisions_one_current', sqlite_where=sa.text('superseded_by_revision_id IS NULL'), postgresql_where=sa.text('superseded_by_revision_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_contract_item_revisions_superseded_by_revision_id'))
        batch_op.drop_index(batch_op.f('ix_contract_item_revisions_contract_item_id'))

    op.drop_table('contract_item_revisions')
    with op.batch_alter_table('accruals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accruals_status'))
        batch_op.drop_index(batch_op.f('ix_accruals_period'))
        batch_op.drop_index(batch_op.f('ix_accruals_created_from_fact_id'))
        batch_op.drop_index(batch_op.f('ix_accruals_contract_item_id'))

    op.drop_table('accruals')
    with op.batch_alter_table('accrual_basis_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accrual_basis_facts_superseded_by_fact_id'))
        batch_op.drop_index(batch_op.f('ix_accrual_basis_facts_contract_item_id'))
        batch_op.drop_index(batch_op.f('ix_accrual_basis_facts_contract_id'))

    op.drop_table('accrual_basis_facts')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_contract_id'))

    op.drop_table('shipments')
    with op.batch_alter_table('sales_match_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_match_candidates_sales_contract_id'))
        batch_op.drop_index(batch_op.f('ix_sales_match_candidates_match_case_id'))

    op.drop_table('sales_match_candidates')
    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_candidates_match_case_id'))
        batch_op.drop_index(batch_op.f('ix_match_candidates_contract_id'))

    op.drop_table('match_candidates')
    with op.batch_alter_table('import_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_runs_evidence_document_id'))

    op.drop_table('import_runs')
    with op.batch_alter_table('evidence_fragments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_fragments_evidence_document_id'))

    op.drop_table('evidence_fragments')
    with op.batch_alter_table('contract_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_items_contract_id'))

    op.drop_table('contract_items')
    with op.batch_alter_table('task_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_exceptions_status'))
        batch_op.drop_index(batch_op.f('ix_task_exceptions_exception_type'))

    op.drop_table('task_exceptions')
    with op.batch_alter_table('sales_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_contracts_sales_contract_no'))
        batch_op.drop_index(batch_op.f('ix_sales_contracts_our_entity'))

    op.drop_table('sales_contracts')
    with op.batch_alter_table('match_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_cases_subject_type'))
        batch_op.drop_index(batch_op.f('ix_match_cases_subject_id'))
        batch_op.drop_index(batch_op.f('ix_match_cases_status'))

    op.drop_table('match_cases')
    with op.batch_alter_table('evidence_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_documents_sha256'))

    op.drop_table('evidence_documents')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_counterparty'))
        batch_op.drop_index(batch_op.f('ix_contracts_contract_no'))

    op.drop_table('contracts')
    with op.batch_alter_table('business_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_events_event_type'))

    op.drop_table('business_events')
    # ### end Alembic commands ###
