"""invoice payment matching phase2a

Revision ID: 2e0e3ca101aa
Revises: e94e038d55f2
Create Date: 2026-08-11 23:42:24.229278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0e3ca101aa'
down_revision: Union[str, Sequence[str], None] = 'e94e038d55f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('match_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_cases_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_cases_subject_type'), ['subject_type'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('invoice_type', sa.String(), nullable=True),
    sa.Column('invoice_no', sa.String(), nullable=True),
    sa.Column('digital_invoice_no', sa.String(), nullable=True),
    sa.Column('external_invoice_key', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('seller', sa.String(), nullable=True),
    sa.Column('buyer', sa.String(), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('invoice_status', sa.String(), nullable=True),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_external_invoice_key'), ['external_invoice_key'], unique=True)

    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('counterparty', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('bank_reference', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('running_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('match_case_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('match_method', sa.String(), nullable=False),
    sa.Column('confirmation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['match_case_id'], ['match_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_allocations_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_allocations_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_allocations_match_case_id'), ['match_case_id'], unique=False)

    op.create_table('invoice_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('specification', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_items_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('match_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_case_id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['match_case_id'], ['match_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_candidates_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_candidates_match_case_id'), ['match_case_id'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('match_case_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('match_method', sa.String(), nullable=False),
    sa.Column('confirmation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['match_case_id'], ['match_cases.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_match_case_id'), ['match_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_payment_id'), ['payment_id'], unique=False)

    with op.batch_alter_table('evidence_fragments', schema=None) as batch_op:
        # server_default backfills existing Phase 1 rows (all EXCEL_ROW)
        # during the table rebuild; dropped right after so future inserts
        # must set it explicitly via the ORM default instead.
        batch_op.add_column(
            sa.Column('fragment_kind', sa.String(), nullable=False, server_default='EXCEL_ROW')
        )
        batch_op.add_column(sa.Column('locator_json', sa.JSON(), nullable=True))
        batch_op.alter_column('sheet_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('row_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('evidence_fragments', schema=None) as batch_op:
        batch_op.alter_column('fragment_kind', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_fragments', schema=None) as batch_op:
        batch_op.alter_column('row_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sheet_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('locator_json')
        batch_op.drop_column('fragment_kind')

    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocations_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_match_case_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_contract_id'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_candidates_match_case_id'))
        batch_op.drop_index(batch_op.f('ix_match_candidates_contract_id'))

    op.drop_table('match_candidates')
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_items_invoice_id'))

    op.drop_table('invoice_items')
    with op.batch_alter_table('invoice_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_allocations_match_case_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_allocations_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_allocations_contract_id'))

    op.drop_table('invoice_allocations')
    op.drop_table('payments')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_external_invoice_key'))

    op.drop_table('invoices')
    with op.batch_alter_table('match_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_cases_subject_type'))
        batch_op.drop_index(batch_op.f('ix_match_cases_subject_id'))
        batch_op.drop_index(batch_op.f('ix_match_cases_status'))

    op.drop_table('match_cases')
    # ### end Alembic commands ###
