"""phase2b accrual period close

Revision ID: 62e13873e978
Revises: 2e0e3ca101aa
Create Date: 2026-08-12 14:46:18.004130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e13873e978'
down_revision: Union[str, Sequence[str], None] = '2e0e3ca101aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_recognition_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('recognition_date', sa.Date(), nullable=False),
    sa.Column('basis', sa.String(), nullable=False),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_recognition_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_recognition_facts_contract_id'), ['contract_id'], unique=False)

    op.create_table('accrual_basis_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('contract_item_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('basis', sa.String(), nullable=False),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['contract_item_id'], ['contract_items.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accrual_basis_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accrual_basis_facts_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accrual_basis_facts_contract_item_id'), ['contract_item_id'], unique=False)

    op.create_table('accruals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('contract_item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('basis', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_from_fact_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_item_id'], ['contract_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accruals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accruals_contract_item_id'), ['contract_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accruals_created_from_fact_id'), ['created_from_fact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accruals_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_accruals_status'), ['status'], unique=False)

    op.create_table('historical_accrual_facts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_period', sa.String(), nullable=False),
    sa.Column('contract_item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('basis', sa.String(), nullable=False),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_item_id'], ['contract_items.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_accrual_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_accrual_facts_contract_item_id'), ['contract_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_accrual_facts_source_period'), ['source_period'], unique=False)

    op.create_table('invoice_item_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_item_id', sa.Uuid(), nullable=False),
    sa.Column('contract_item_id', sa.Uuid(), nullable=False),
    sa.Column('allocated_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('allocated_net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('confirmation_type', sa.String(), nullable=False),
    sa.Column('source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_item_id'], ['contract_items.id'], ),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['invoice_items.id'], ),
    sa.ForeignKeyConstraint(['source_fragment_id'], ['evidence_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_item_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_item_allocations_contract_item_id'), ['contract_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_item_allocations_invoice_item_id'), ['invoice_item_id'], unique=False)

    op.create_table('accrual_reversals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('accrual_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('invoice_item_allocation_id', sa.Uuid(), nullable=False),
    sa.Column('reversed_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reversed_estimated_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accrual_id'], ['accruals.id'], ),
    sa.ForeignKeyConstraint(['invoice_item_allocation_id'], ['invoice_item_allocations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accrual_reversals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accrual_reversals_accrual_id'), ['accrual_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accrual_reversals_invoice_item_allocation_id'), ['invoice_item_allocation_id'], unique=False)

    with op.batch_alter_table('contract_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_item_key', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_contract_item_source_key', ['contract_id', 'source_item_key'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_contract_item_source_key', type_='unique')
        batch_op.drop_column('source_item_key')

    with op.batch_alter_table('accrual_reversals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accrual_reversals_invoice_item_allocation_id'))
        batch_op.drop_index(batch_op.f('ix_accrual_reversals_accrual_id'))

    op.drop_table('accrual_reversals')
    with op.batch_alter_table('invoice_item_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_item_allocations_invoice_item_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_item_allocations_contract_item_id'))

    op.drop_table('invoice_item_allocations')
    with op.batch_alter_table('historical_accrual_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_accrual_facts_source_period'))
        batch_op.drop_index(batch_op.f('ix_historical_accrual_facts_contract_item_id'))

    op.drop_table('historical_accrual_facts')
    with op.batch_alter_table('accruals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accruals_status'))
        batch_op.drop_index(batch_op.f('ix_accruals_period'))
        batch_op.drop_index(batch_op.f('ix_accruals_created_from_fact_id'))
        batch_op.drop_index(batch_op.f('ix_accruals_contract_item_id'))

    op.drop_table('accruals')
    with op.batch_alter_table('accrual_basis_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accrual_basis_facts_contract_item_id'))
        batch_op.drop_index(batch_op.f('ix_accrual_basis_facts_contract_id'))

    op.drop_table('accrual_basis_facts')
    with op.batch_alter_table('cost_recognition_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_recognition_facts_contract_id'))

    op.drop_table('cost_recognition_facts')
    # ### end Alembic commands ###
