"""initial schema

Revision ID: e94e038d55f2
Revises: 
Create Date: 2026-08-11 21:17:49.783746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94e038d55f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_events_event_type'), 'business_events', ['event_type'], unique=False)
    op.create_table('evidence_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_documents_sha256'), 'evidence_documents', ['sha256'], unique=True)
    op.create_table('task_exceptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exception_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_exceptions_exception_type'), 'task_exceptions', ['exception_type'], unique=False)
    op.create_index(op.f('ix_task_exceptions_status'), 'task_exceptions', ['status'], unique=False)
    op.create_table('evidence_fragments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=False),
    sa.Column('sheet_name', sa.String(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['evidence_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_document_id', 'sheet_name', 'row_number', name='uq_fragment_location')
    )
    op.create_index(op.f('ix_evidence_fragments_evidence_document_id'), 'evidence_fragments', ['evidence_document_id'], unique=False)
    op.create_table('import_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evidence_document_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('is_reimport', sa.Boolean(), nullable=False),
    sa.Column('contracts_created_count', sa.Integer(), nullable=False),
    sa.Column('contract_items_created_count', sa.Integer(), nullable=False),
    sa.Column('business_key_conflicts_detected_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['evidence_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_runs_evidence_document_id'), 'import_runs', ['evidence_document_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_no', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('counterparty', sa.String(), nullable=True),
    sa.Column('buyer', sa.String(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('current_source_fragment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_source_fragment_id'], ['evidence_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_no'), 'contracts', ['contract_no'], unique=False)
    op.create_table('contract_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('specification', sa.String(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('current_source_fragment_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['current_source_fragment_id'], ['evidence_fragments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_items_contract_id'), 'contract_items', ['contract_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_items_contract_id'), table_name='contract_items')
    op.drop_table('contract_items')
    op.drop_index(op.f('ix_contracts_contract_no'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_import_runs_evidence_document_id'), table_name='import_runs')
    op.drop_table('import_runs')
    op.drop_index(op.f('ix_evidence_fragments_evidence_document_id'), table_name='evidence_fragments')
    op.drop_table('evidence_fragments')
    op.drop_index(op.f('ix_task_exceptions_status'), table_name='task_exceptions')
    op.drop_index(op.f('ix_task_exceptions_exception_type'), table_name='task_exceptions')
    op.drop_table('task_exceptions')
    op.drop_index(op.f('ix_evidence_documents_sha256'), table_name='evidence_documents')
    op.drop_table('evidence_documents')
    op.drop_index(op.f('ix_business_events_event_type'), table_name='business_events')
    op.drop_table('business_events')
    # ### end Alembic commands ###
